/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health snapshot
         * @description Return the current health snapshot.
         *
         *     Phase 0 stub: always returns a fixed healthy example. The real handler
         *     (Phase 2B) calls `services.health.HealthService.get_health()` and returns
         *     HTTP 503 with the same body shape when the database is unreachable.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Realtime per-SDR status
         * @description Return the realtime per-SDR view — identical payload to the SSE `snapshot` event.
         *
         *     Phase 0 stub: always returns one fixed example device. The real handler
         *     (Phase 2B) calls `services.device_registry.DeviceRegistry.list_statuses()`.
         */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Realtime fleet events (Server-Sent Events)
         * @description Open an SSE stream of fleet events.
         *
         *     Response is `text/event-stream` and is not modelled as a single JSON
         *     schema — the frozen shapes of each named event are documented in
         *     `schemas/device.py`, `schemas/events.py` and `schemas/health.py`.
         */
        get: operations["get_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List configured and detected devices
         * @description Return every configured device plus every detected-but-unconfigured one.
         *
         *     Phase 0 stub: fixed example data. The real handler (Phase 2B) calls
         *     `services.device_registry.DeviceRegistry.list_records()` and
         *     `services.port_allocator.PortAllocatorService.suggest_next()`.
         */
        get: operations["list_devices_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a device's persisted configuration
         * @description Remove a device's persisted configuration, stopping its pair first if running.
         *
         *     Phase 0 stub: always succeeds. The real handler (Phase 2B) calls
         *     `services.device_registry.DeviceRegistry.delete()` and returns
         *     `404 unknown_device` for an unconfigured device_id.
         */
        delete: operations["delete_device_api_devices__device_id__delete"];
        options?: never;
        head?: never;
        /**
         * Create or update a device's configuration
         * @description Upsert one device's configuration; creates the row on first call for a detected device.
         *
         *     Phase 0 stub: echoes the fixed example record regardless of `patch`. The
         *     real handler (Phase 2B) calls
         *     `services.device_registry.DeviceRegistry.apply_patch()` and maps its
         *     exceptions to `404 unknown_device` / `409 port_conflict` /
         *     `409 name_conflict` / `422 device_unidentified`.
         */
        patch: operations["patch_device_api_devices__device_id__patch"];
        trace?: never;
    };
    "/api/devices/{device_id}/serial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flash a unique serial to the dongle's EEPROM
         * @description Begin the guarded EEPROM serial-flash flow; the outcome arrives via SSE `notice`.
         *
         *     Phase 0 stub: always returns `202 Accepted` with a fixed operation id.
         *     The real handler (Phase 3A) delegates to `services.eeprom.EepromService`
         *     and never performs the flash inline.
         */
        post: operations["flash_serial_api_devices__device_id__serial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sdrs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The Sentinel-consumed SDR export (versioned)
         * @description Return every configured device mapped onto Sentinel's `SdrRadio` field names.
         */
        get: operations["get_sdrs_v1_api_v1_sdrs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sdrs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Permanent alias for the current stable /v1/sdrs
         * @description Permanent convenience alias serving the current stable SDR export version.
         */
        get: operations["get_sdrs_alias_api_sdrs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClientCounts
         * @description Per-port connected-client counts from `SocketStatsSource`.
         *
         *     Every field is nullable and advisory: `None` on platforms without
         *     `/proc/net/tcp` (architecture decision — always nullable, never a hard
         *     dependency for status reporting).
         */
        ClientCounts: {
            /** Iq */
            iq?: number | null;
            /** Control */
            control?: number | null;
        };
        /**
         * DeviceCounts
         * @description Per-state device tallies surfaced in the health snapshot.
         */
        DeviceCounts: {
            /** Present */
            present: number;
            /** Configured */
            configured: number;
            /** Streaming */
            streaming: number;
            /** Degraded */
            degraded: number;
            /** Error */
            error: number;
            /** Needs Identification */
            needs_identification: number;
        };
        /**
         * DevicePatch
         * @description `PATCH /api/devices/{device_id}` request body — all fields optional, one required.
         *
         *     `extra="forbid"` rejects unknown fields outright rather than silently
         *     ignoring operator typos (architecture §12.12).
         */
        DevicePatch: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Output Port */
            output_port?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Center Hz */
            center_hz?: number | null;
            /** Sample Rate */
            sample_rate?: number | null;
            /** Gain Db */
            gain_db?: number | null;
            /** Gain Auto */
            gain_auto?: boolean | null;
            /** Ppm Correction */
            ppm_correction?: number | null;
            /** Bias Tee */
            bias_tee?: boolean | null;
            /** Direct Sampling */
            direct_sampling?: (0 | 1 | 2) | null;
        };
        /**
         * DeviceRecord
         * @description One device's configuration-centric record — `GET /api/devices` item and PATCH response.
         */
        DeviceRecord: {
            /** Device Id */
            device_id: string;
            /** Record Id */
            record_id: number | null;
            /**
             * Identity Kind
             * @enum {string}
             */
            identity_kind: "serial" | "usb";
            /** Identity Key */
            identity_key: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Output Port */
            output_port?: number | null;
            /** Control Port */
            control_port?: number | null;
            /** Enabled */
            enabled: boolean;
            /** Center Hz */
            center_hz?: number | null;
            /** Sample Rate */
            sample_rate?: number | null;
            /** Gain Db */
            gain_db?: number | null;
            /** Gain Auto */
            gain_auto: boolean;
            /** Ppm Correction */
            ppm_correction: number;
            /**
             * Bias Tee
             * @description Bias-T power, nullable
             */
            bias_tee?: boolean | null;
            /**
             * Direct Sampling
             * @description Direct-sampling mode, nullable
             */
            direct_sampling?: (0 | 1 | 2) | null;
            /** Present */
            present: boolean;
            /** Needs Identification */
            needs_identification: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "detected" | "configured" | "starting" | "streaming" | "degraded" | "stopped" | "error";
            /** Last Topology Path */
            last_topology_path: string;
            /** Last Serial */
            last_serial: string;
            /** Last Seen At */
            last_seen_at?: number | null;
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
        };
        /**
         * DeviceStatus
         * @description One device's realtime status — the `GET /api/status` and SSE payload shape.
         */
        DeviceStatus: {
            /**
             * Device Id
             * @description The public key: "serial:<value>" or "usb:<path>"
             */
            device_id: string;
            /**
             * Record Id
             * @description The DB surrogate key; null for a detected device
             */
            record_id: number | null;
            /**
             * Identity Kind
             * @enum {string}
             */
            identity_kind: "serial" | "usb";
            /** Identity Key */
            identity_key: string;
            /** Needs Identification */
            needs_identification: boolean;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * State
             * @enum {string}
             */
            state: "detected" | "configured" | "starting" | "streaming" | "degraded" | "stopped" | "error";
            /**
             * State Since
             * @description Unix ms this state began
             */
            state_since: number;
            /**
             * State Reason
             * @description Machine code, non-null in error
             */
            state_reason?: string | null;
            /** Present */
            present: boolean;
            /** Enabled */
            enabled: boolean;
            /** @description Null when the device is absent */
            usb?: components["schemas"]["UsbInfo"] | null;
            /** @description Populated instead of `usb` for an absent configured device */
            usb_last_known?: components["schemas"]["UsbLastKnownInfo"] | null;
            /** @description Null for an unconfigured device */
            output?: components["schemas"]["OutputInfo"] | null;
            /** @description Null until control_follower's first state event */
            tuner?: components["schemas"]["TunerInfo"] | null;
            processes?: components["schemas"]["ProcessInfo"] | null;
            clients?: components["schemas"]["ClientCounts"] | null;
            /** Last Seen At */
            last_seen_at?: number | null;
        };
        /**
         * DevicesListResponse
         * @description `GET /api/devices` body: every configured and every detected device.
         */
        DevicesListResponse: {
            /** Devices */
            devices: components["schemas"]["DeviceRecord"][];
            /** Port Suggestion */
            port_suggestion: number | null;
            constraints: components["schemas"]["PortConstraints"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description `GET /api/health` body. Auth-exempt; 503 only when the database is unreachable.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "unhealthy";
            /** Version */
            version: string;
            /**
             * Started At
             * @description Unix ms the process started
             */
            started_at: number;
            /** Uptime S */
            uptime_s: number;
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            hotplug: components["schemas"]["HotplugHealth"];
            devices: components["schemas"]["DeviceCounts"];
        };
        /**
         * HotplugHealth
         * @description Whether the primary hotplug mechanism (udev) or only the reconcile fallback is active.
         */
        HotplugHealth: {
            /**
             * Source
             * @enum {string}
             */
            source: "udev" | "reconcile";
            /** Healthy */
            healthy: boolean;
            /** Last Event At */
            last_event_at?: number | null;
        };
        /**
         * OutputInfo
         * @description The public IQ/control endpoint for a configured device.
         */
        OutputInfo: {
            /**
             * Host
             * @description The Pi's advertised LAN address
             */
            host: string;
            /**
             * Iq Port
             * @description The relay's public IQ port P
             */
            iq_port: number;
            /**
             * Control Port
             * @description P + 2, the NDJSON control port
             */
            control_port: number;
        };
        /**
         * PortConstraints
         * @description Mirrors the port-allocator rule table so the UI can validate inline.
         *
         *     Advisory only — the server always re-validates on `PATCH` (architecture §7.4).
         */
        PortConstraints: {
            /** Port Min */
            port_min: number;
            /** Port Max */
            port_max: number;
            /** Reserved */
            reserved: number[];
            /** Internal Range */
            internal_range: [
                number,
                number
            ];
            /** In Use */
            in_use: number[];
        };
        /**
         * ProcessInfo
         * @description Supervisor-owned process/lifecycle telemetry for a device's running pair.
         */
        ProcessInfo: {
            /** Rtl Tcp Pid */
            rtl_tcp_pid?: number | null;
            /** Relay Pid */
            relay_pid?: number | null;
            /**
             * Internal Port
             * @description The loopback rtl_tcp port
             */
            internal_port?: number | null;
            /**
             * Restarts
             * @default 0
             */
            restarts: number;
            /** Last Restart At */
            last_restart_at?: number | null;
            /** Last Exit Code */
            last_exit_code?: number | null;
        };
        /**
         * SdrExportItem
         * @description One configured device, mapped onto Sentinel's `SdrRadio` / `RadioIn` field names.
         *
         *     Field-by-field mapping and rationale: architecture §7.8.
         */
        SdrExportItem: {
            /**
             * Sentry Device Id
             * @description Idempotency key for Sentinel's import
             */
            sentry_device_id: string;
            /** Name */
            name: string;
            /** Host */
            host: string;
            /**
             * Port
             * @description The relay's IQ port P
             */
            port: number;
            /**
             * Control Port
             * @description P + 2, sent for verification only
             */
            control_port: number;
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Bandwidth
             * @description Sentry's sample_rate
             */
            bandwidth?: number | null;
            /**
             * Rf Gain
             * @description Sentry's gain_db; null when AGC
             */
            rf_gain?: number | null;
            /**
             * Agc
             * @description Sentry's gain_auto
             */
            agc?: boolean | null;
            /**
             * Available
             * @description Display-only: grey out rather than hide when false
             */
            available: boolean;
            /**
             * State
             * @description Display-only device state
             */
            state: string;
        };
        /**
         * SdrExportResponse
         * @description `GET /api/v1/sdrs` and `GET /api/sdrs` (permanent alias) body.
         */
        SdrExportResponse: {
            /**
             * Api Version
             * @default 1
             */
            api_version: number;
            /** Generated At */
            generated_at: number;
            source: components["schemas"]["SdrExportSource"];
            /**
             * Control Port Offset
             * @description Sentinel already computes port + this offset
             * @default 2
             */
            control_port_offset: number;
            /** Sdrs */
            sdrs: components["schemas"]["SdrExportItem"][];
        };
        /**
         * SdrExportSource
         * @description Identifies the Sentry instance that produced this export.
         */
        SdrExportSource: {
            /**
             * Name
             * @default sentry
             * @constant
             */
            name: "sentry";
            /** Version */
            version: string;
            /**
             * Host
             * @description Never 0.0.0.0 or a container-internal address
             */
            host: string;
            /** Http Port */
            http_port: number;
        };
        /**
         * SerialFlashAccepted
         * @description `202 Accepted` body; the outcome arrives later as an SSE `notice`.
         */
        SerialFlashAccepted: {
            /** Device Id */
            device_id: string;
            /**
             * Operation Id
             * @description Correlates this request with its SSE notice events
             */
            operation_id: string;
            /**
             * Status
             * @constant
             */
            status: "in_progress";
            /**
             * Requires Replug
             * @description A physical replug is required before the new serial is visible
             * @default true
             */
            requires_replug: boolean;
        };
        /**
         * SerialFlashRequest
         * @description Request body for flashing a unique serial to a dongle's EEPROM.
         */
        SerialFlashRequest: {
            /** Serial */
            serial: string;
            /**
             * Confirm
             * @description Must be exactly true; a destructive hardware write requires explicit intent
             * @constant
             */
            confirm: true;
        };
        /**
         * StatusResponse
         * @description `GET /api/status` and the SSE `snapshot` event body.
         */
        StatusResponse: {
            /**
             * Generated At
             * @description Unix ms this snapshot was assembled
             */
            generated_at: number;
            /**
             * Sdrs
             * @description Sorted by usb.topology_path; absent devices last
             */
            sdrs: components["schemas"]["DeviceStatus"][];
        };
        /**
         * TunerInfo
         * @description The live tuner state as last observed via `control_follower` (architecture §7.2).
         */
        TunerInfo: {
            /** Center Hz */
            center_hz: number;
            /** Sample Rate */
            sample_rate: number;
            /** Gain Db */
            gain_db: number;
            /** Gain Auto */
            gain_auto: boolean;
            /**
             * Locked
             * @description Whether another owner currently holds the tuning token
             */
            locked: boolean;
            /**
             * Observed At
             * @description Unix ms this state was last observed on P+2
             */
            observed_at: number;
            /**
             * Bias Tee
             * @description Bias-T power state, when the dongle supports it
             */
            bias_tee?: boolean | null;
            /**
             * Direct Sampling
             * @description Direct-sampling mode (0=off, 1=I-ADC, 2=Q-ADC), when in use
             */
            direct_sampling?: (0 | 1 | 2) | null;
        };
        /**
         * UsbInfo
         * @description The live USB descriptor and topology for a present device (architecture §7.2).
         */
        UsbInfo: {
            /**
             * Topology Path
             * @description Bus-port path, e.g. "1-1.4.2"
             */
            topology_path: string;
            /** Bus Number */
            bus_number: number;
            /**
             * Port Chain
             * @description The port path as integers, e.g. (1, 4, 2)
             */
            port_chain: number[];
            /**
             * Hub Depth
             * @description len(port_chain) - 1
             */
            hub_depth: number;
            /**
             * Device Address
             * @description Kernel devnum; unstable, display only
             */
            device_address: number;
            /**
             * Vendor Id
             * @description Lowercase hex, no "0x", e.g. "0bda"
             */
            vendor_id: string;
            /**
             * Product Id
             * @description Lowercase hex, no "0x", e.g. "2838"
             */
            product_id: string;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Product */
            product?: string | null;
            /**
             * Serial
             * @description The raw reported iSerial
             */
            serial?: string | null;
            /**
             * Driver
             * @description Bound kernel driver name, if any
             */
            driver?: string | null;
            /**
             * Driver Conflict
             * @description True when the DVB kernel driver is bound instead of the userspace driver
             */
            driver_conflict: boolean;
        };
        /**
         * UsbLastKnownInfo
         * @description A reduced USB description for a configured device that is currently absent.
         *
         *     Populated from the persisted `last_*` columns so an absent device still
         *     renders identifiably in the UI (architecture §7.2).
         */
        UsbLastKnownInfo: {
            /** Topology Path */
            topology_path: string;
            /** Vendor Id */
            vendor_id: string;
            /** Product Id */
            product_id: string;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Product */
            product?: string | null;
            /** Serial */
            serial?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_devices_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicesListResponse"];
                };
            };
        };
    };
    delete_device_api_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Either "serial:<value>" or "usb:<topology_path>" */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_device_api_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Either "serial:<value>" or "usb:<topology_path>" */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flash_serial_api_devices__device_id__serial_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Either "serial:<value>" or "usb:<topology_path>" */
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerialFlashRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerialFlashAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sdrs_v1_api_v1_sdrs_get: {
        parameters: {
            query?: {
                include_disabled?: boolean;
                available_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SdrExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sdrs_alias_api_sdrs_get: {
        parameters: {
            query?: {
                include_disabled?: boolean;
                available_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SdrExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
